use SP_MEDICAL_GROUP_2TT_Gabriel_Iwazaki

-- VINCULOU A TABELA PRONTUARIO COM A TABELA CONSULTAS
SELECT * FROM PRONTUARIO INNER JOIN CONSULTAS ON PRONTUARIO.ID = CONSULTAS.ID_PRONTUARIO

-- VINCULOU A TABELA PRONTUARIO COM AS TABELAS CONSULTAS E MEDICOS
SELECT * FROM PRONTUARIO INNER JOIN CONSULTAS ON PRONTUARIO.ID = CONSULTAS.ID_PRONTUARIO INNER JOIN MEDICOS ON MEDICOS.ID = CONSULTAS.ID_MEDICO

-- VINCULOU A TABELA ESPECIALIDADES COM A TABELA MEDICOS
SELECT * FROM ESPECIALIDADES INNER JOIN MEDICOS ON ESPECIALIDADES.ID = MEDICOS.ID_ESPECIALIDADE

-- VINCULOU A TABELA CLINICAS COM A TABELA MEDICOS
SELECT * FROM CLINICA INNER JOIN MEDICOS ON CLINICA.ID = MEDICOS.ID_CLINICA

-- INSERE UM NOVO USUARIO
INSERT INTO USUARIOS (ID_TIPO_USUARIO, EMAIL, SENHA)
VALUES (3, 'paloma@gmail.com', '123456')

-- DELETA UM USUARIO
DELETE FROM USUARIOS WHERE ID = '13'

-- RETORNA A QUANTIDADE DE USUARIOS
SELECT COUNT (*) FROM USUARIOS

-- CONVERTE A DATA DE NASCIMENTO PARA MM-DD-YYYY
SELECT CONVERT (VARCHAR(10), DT_NASCIMENTO, 103) FROM PRONTUARIO

-- RETORNA OS MEDICOS POR ESPECIALIDADES
CREATE PROCEDURE spRetornarMedicosPorEspecialidades AS 
SELECT COUNT(*) FROM MEDICOS WHERE ID_ESPECIALIDADE = '17'
EXEC spRetornarMedicosPorEspecialidades

-- CALCULA A IDADE DO USUARIO
CREATE PROCEDURE spCalcularIdadeUsuario AS
SELECT FLOOR (DATEDIFF(DAY,DT_NASCIMENTO, GETDATE())/365.25) FROM PRONTUARIO
EXEC spCalcularIdadeUsuario

