CREATE DATABASE SP_MEDICAL_GROUP_2TT_Gabriel_Iwazaki

CREATE TABLE CLINICA(
ID INT IDENTITY PRIMARY KEY,
NOME VARCHAR(250) NOT NULL,
CNPJ CHAR(14) NOT NULL UNIQUE,
ENDEREÇO VARCHAR(250) NOT NULL UNIQUE,
RAZAO_SOCIAL VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE ESPECIALIDADES(
ID INT IDENTITY PRIMARY KEY,
NOME VARCHAR(250) NOT NULL UNIQUE,
);

CREATE TABLE TIPO_USUARIO(
ID INT IDENTITY PRIMARY KEY,
TIPO VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE USUARIOS(
ID INT IDENTITY PRIMARY KEY,
ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPO_USUARIO(ID) NOT NULL,
EMAIL VARCHAR(250) NOT NULL UNIQUE,
SENHA VARCHAR(250) NOT NULL
);

CREATE TABLE MEDICOS(
ID INT IDENTITY PRIMARY KEY,
CRM CHAR(5) NOT NULL,
NOME VARCHAR(250) NOT NULL,
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID) NOT NULL,
ID_ESPECIALIDADE INT FOREIGN KEY REFERENCES ESPECIALIDADES(ID) NOT NULL,
ID_CLINICA INT FOREIGN KEY REFERENCES CLINICA(ID) NOT NULL
);

CREATE TABLE SITUACAO (
ID INT IDENTITY PRIMARY KEY,
TIPO VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE PRONTUARIO(
ID INT IDENTITY PRIMARY KEY,
NOME VARCHAR(250) NOT NULL,
ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID) NOT NULL,
DT_NASCIMENTO DATE NOT NULL,
TELEFONE VARCHAR(20) NOT NULL UNIQUE,
RG VARCHAR(9) NOT NULL UNIQUE,
CPF CHAR(11) NOT NULL UNIQUE,
ENDEREÇO VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE CONSULTAS (
ID INT IDENTITY PRIMARY KEY,
ID_PRONTUARIO INT FOREIGN KEY REFERENCES PRONTUARIO(ID) NOT NULL,
ID_MEDICO INT FOREIGN KEY REFERENCES MEDICOS(ID) NOT NULL,
DT_CONSULTA DATETIME NOT NULL,
ID_SITUACAO INT FOREIGN KEY REFERENCES SITUACAO(ID) NOT NULL,
DESCRICAO TEXT
);